### PR TITLE
Fix hint in answer breaking markdown content

### LINKED ISSUE #46: Appending "correct" / "incorrect" to answers breaks markdown formatting
After submitting and answer we append if the user answered correctly or not.

image

It seems that if we [append to the text](https://github.com/christophblessing/quiz-recap/blob/main/src/components/Answers.tsx#L50), it breaks the formatting.

```
<code>
const markdown = "awesome";
</code>
```

becomes

```
<code>const markdown = "awesome";
``` - incorrect answer
</code>
```

### PR DESCRIPTION
**Pull request by christophblessing**
## Description

This PR fixes the hint if the user answered a question correctly in answer breaking markdown content.

If you put a block of code in the markdown content, it will be strangely formatted after answering a question because we append `- text` to it.

### Before

Screenshot 2024-04-15 at 17 15 13

### After

Screenshot 2024-04-15 at 17 14 27

## Decisions / Choices I made

I decided to fix it by adding a separate paragraph instead of appending the text to the content.
This way we don't change the content of the `Markdown` component.

Additionally, I think it made sense to also change the wording in the locales and right align it.
Input on the styling is appreciated.

Closes #46

## Checklist

- [x] All checks pass successfully
- [x] All related commits are squashed together
- [x] The code follows the project's coding standards
- [x] The changes are properly documented / the relevant documentation is updated (if applicable)
- [x] Appropriate labels are added to this pull request

### CODE REVIEW

File: src/locales/de.ts [hunk 1]
```diff
@@ -38,8 +38,8 @@ const de = {
     new: 'Neues Quiz',
   },
   answer: {
-    correct: ' - richtige Antwort',
-    incorrect: ' - falsche Antwort',
+    correct: 'Richtige Antwort',
```
Comment (JuliaCasamitjana) [inline src/locales/de.ts:41]: As discussed, let's omit "Answer" also in german

**Review by JuliaCasamitjana — APPROVED** [review]
