### PR TITLE
Form progress should include number of questions removed from the QuestionsPool

### LINKED ISSUE #49: Form legend does not update correctly
Wrongly answered questions with no remaining attempts do no increase the counter.
They should increase the counter just as correctly answered questions do.

In an extreme example, I would not answer any question correctly and it would say "1 of 10" at the very last question.

### PR DESCRIPTION
**Pull request by JuliaCasamitjana**
## What does this change?

This PR fixes a bug with the quiz progress. It was only counting correctly answered questions but it should also include questions that have been removed from the pool because attempts have expired. This way, right before the quiz ends the progress is completed (e.g. 10 of 10)

Adds regressions test. 

Fixes #49

### CODE REVIEW

File: src/components/Form.tsx [hunk 1]
```diff
@@ -119,7 +119,7 @@ const Form = ({
   };
 
   const handleNextQuestion = () => {
-    if (isCorrect) {
+    if (isCorrect || question.remainingAttempts === 1) {
```
Comment (christophblessing) [inline src/components/Form.tsx:122]: Works great!

Alternatively, this logic could be extracted to a hook:

```
  useEffect(() => {
    if (!submitted) {
      setQuestionIndexText(numberOfQuestions - questionsPool.length + 1);
    }
  }, [
    numberOfQuestions,
    questionsPool.length,
    setQuestionIndexText,
    submitted,
  ]);
```

It would set the index depending on the pool size. The only not straight forward thing is the dependence on the `submitted`, but otherwise it would set the index higher as soon as you answered the question (and not on the next).

What do you think?

**Review by christophblessing — APPROVED** [review]

File: src/components/Form.tsx (hunk 1 above)
Comment (JuliaCasamitjana) [reply src/components/Form.tsx]: Looks good! I've added your suggestion. 👍
